// Generated by LiveScript 1.4.0
(function(){
  var cols;
  cols = 40;
  function map(f, list){
    var res, i$, len$, itm;
    res = [];
    for (i$ = 0, len$ = list.length; i$ < len$; ++i$) {
      itm = list[i$];
      res.push(f(itm));
    }
    return res;
  }
  function any(list){
    var i$, len$, elem;
    for (i$ = 0, len$ = list.length; i$ < len$; ++i$) {
      elem = list[i$];
      if (elem) {
        return true;
      }
    }
    return false;
  }
  function wcswidth(text){
    return text.length;
  }
  function wrap(line){
    var pat, prev, m, cur, curw, rest;
    if (wcswidth(line) <= cols) {
      return [line];
    } else {
      pat = /\s+/g;
      prev = 0;
      while (m = pat.exec(line)) {
        cur = m.index + m[0].length;
        curw = wcswidth(line.substr(0, cur));
        if (curw > cols) {
          break;
        } else {
          prev = cur;
        }
      }
      rest = wrap(line.substr(prev));
      return [line.substr(0, prev)].concat(rest);
    }
  }
  function txProcess(text){
    var lines, toobig, autowrap, reallines, i$, ref$, len$, paragraph, line;
    lines = text.split('\n');
    toobig = function(line){
      return wcswidth(line) > cols;
    };
    autowrap = any(map(toobig, lines));
    reallines = [];
    if (autowrap) {
      for (i$ = 0, len$ = (ref$ = text.split(/[\t \v\f\r]*(?:\n[\t \v\f\r]*)+/)).length; i$ < len$; ++i$) {
        paragraph = ref$[i$];
        Array.prototype.push.apply(reallines, wrap(paragraph));
        reallines.push('');
      }
    } else {
      for (i$ = 0, len$ = lines.length; i$ < len$; ++i$) {
        line = lines[i$];
        Array.prototype.push.apply(reallines, wrap(line));
      }
    }
    return reallines;
  }
  $(function(){
    var position, basePosition, referenceTime, speed, defaultSpeed, scr, origText, skipTo, setSpeed, setDefaultSpeed, update, reload;
    position = 0;
    basePosition = 0;
    referenceTime = 0;
    speed = 0;
    defaultSpeed = 0.6;
    scr = $('#script');
    origText = "";
    skipTo = function(line){
      basePosition = line;
      position = basePosition;
      referenceTime = performance.now();
      if (speed === 0) {
        setSpeed(1);
        return setSpeed(0);
      }
    };
    setSpeed = function(spd){
      var needUpd;
      needUpd = speed === 0;
      speed = spd;
      basePosition = position;
      referenceTime = performance.now();
      if (speed !== 0 && needUpd) {
        return update();
      }
    };
    setDefaultSpeed = function(spd){
      defaultSpeed = spd;
      $('#gauge').css({
        height: 10 * defaultSpeed * 1.2 + "em"
      });
      if (speed !== 0) {
        return setSpeed(defaultSpeed);
      }
    };
    setDefaultSpeed(0.6);
    update = function(){
      var now;
      if (speed !== 0) {
        scr.css({
          willChange: "transform"
        });
        now = performance.now();
        position = basePosition + speed * (now - referenceTime) / 1000;
        scr.css({
          transform: "translateY(" + -position * 1.2 + "em)"
        });
        return requestAnimationFrame(update);
      } else {
        return scr.css({
          willChange: ""
        });
      }
    };
    reload = function(){
      var i$, ref$, len$, line, results$ = [];
      scr.html('');
      for (i$ = 0, len$ = (ref$ = txProcess(origText)).length; i$ < len$; ++i$) {
        line = ref$[i$];
        results$.push(scr.append($('<div></div>').addClass('scriptrow').text(line)));
      }
      return results$;
    };
    $('#reset').click(function(){
      return skipTo(0);
    });
    $('#faster').click(function(){
      setSpeed(speed === 0 ? defaultSpeed : 0);
      return console.log("Set speed to " + speed);
    });
    $('#settext').click(function(){
      $('#pastebox').addClass('pb-active');
      return $('#nowset').removeClass('hiddenbutton');
    });
    $('#nowset').click(function(){
      setSpeed(0);
      origText = $('#pastebox').val();
      reload();
      $('#pastebox').val('');
      $('#pastebox').removeClass('pb-active');
      return $('#nowset').addClass('hiddenbutton');
    });
    $('#slower').click(function(){
      return setDefaultSpeed(defaultSpeed - 0.05);
    });
    return $('#flower').click(function(){
      return setDefaultSpeed(defaultSpeed + 0.05);
    });
  });
}).call(this);

//# sourceMappingURL=tpscript.js.map
